# Exercise configuration file


# Structure:
#
# An exercise contains a list of notebooks under the node notebooks.
# Each notebooks is required to specify the package_name, namely the package where it has to be copied in the ros ws,
# and a name that is the name of the notebook in the notebooks folder.
#
#  files:
#    - notebook:
#        target: ""
#        name: ""
#    - notebook:
#        target: ""
#        name: ""
#    - notebook:
#        target: ""
#        name: ""
#
# agent_base: "duckietown_baseline" # currently not implemented, the agent base image to use
# ws_dir: "exercise_ws" # directory that contains the code
# agent_run_cmd: "run_all.sh" # the script in "launchers" to run the agent with

agent_base: "duckietown_baseline" # currently not implemented, the agent base image to use
ws_dir: "solution" # directory that contains the code
lab_dir: .
agent_run_cmd: "default.sh" # the script in "launchers" to run the agent with
ros: true

files:
  - notebook:
      target_dir: "exercise_ws/src/controller_pkg/src"
      input_file: "notebooks/PID_controller.ipynb"